name: react-bootstrap-tutorial

on:
  push:
    branches:
    - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/experiment
      - run: npm install
      - run: npm run build
      - run: npm test
