name: react-bootstrap-tutorial

on:
  push:
    branches:
    - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: billhstan/react-bootstrap-tutorial/.github/workflows/workflow@master
    - uses: billhstan/react-bootstrap-tutorial@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
