name: Example workflow for S3 Deploy
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: npm

        - name: Build
          run: npm build

        - name: Deploy
          uses: billhstan/react-bootstrap-tutorial

          with:
            folder: build
            bucket: ${{ secrets.AWS_S3_BUCKET }}
  
            
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true

           